spring:
  redis:
    host: localhost
    password: password
    port: 6379
  codec:
    max-in-memory-size: 1MB

marvel-api:
  base-url: 'https://gateway.marvel.com/v1/public'
  public-key: ${MARVEL_API_PUBLIC_KEY}
  private-key: ${MARVEL_API_PRIVATE_KEY}
  page-limit: 100

springdoc:
  version: '@springdoc.version@'
  api-docs.path: /api-docs
  swagger-ui.path: /api-ui
  paths-to-match: /characters/**

#logging.level.dev.cinnes.marvel: debug