spring:
  redis:
    host: localhost
    password: password
    port: 6379
  codec:
    max-in-memory-size: 1MB

app:
  base-url: "https://gateway.marvel.com/v1/public"
  public-key: "7b0e55f6a4544e6f2165a9359dabeb27"
  private-key: "8ec4e3d8cb93baaf0d005526c14c07ae8717cc78"
  page-limit: 100