spring:
  redis:
    host: localhost
    password: password
    port: 6379
  codec:
    max-in-memory-size: 1MB

app:
  base-url: "https://gateway.marvel.com/v1/public"
  public-key: ${MARVEL_API_PUBLIC_KEY}
  private-key: ${MARVEL_API_PRIVATE_KEY}
  page-limit: 100