spring:
  cloud.gcp.secretmanager.enabled: true
  redis:
    host: localhost
    password: password
    port: 6379
  codec:
    max-in-memory-size: 1MB

app:
  initialize-data: false
  supported-languages: en,es,it,fr,de
  marvel-api:
    base-url: 'https://gateway.marvel.com/v1/public'
    public-key: ${sm://marvel-api-public-key}
    private-key: ${sm://marvel-api-private-key}
    page-limit: 100


springdoc:
  version: '@springdoc.version@'
  api-docs.path: /api-docs
  swagger-ui.path: /api-ui
  paths-to-match: /characters/**

#logging.level.dev.cinnes.marvel: debug